In [1]:
import numpy as np
import pandas as pd

In [2]:
import pickle
matches = pickle.load(open('dataset_1.pkl' , 'rb'))

In [3]:
matches

,innings,info.city,info.dates,info.gender,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.decision,info.toss.winner,info.umpires,info.venue,match_id
0,"[{'1st innings': {'team': 'Australia', 'delive...",Brisbane,[2017-01-13],male,ODI,Australia,50,[MS Wade],"[Australia, Pakistan]",bat,Australia,"[MD Martell, C Shamshuddin]","Brisbane Cricket Ground, Woolloongabba",1
1,"[{'1st innings': {'team': 'Australia', 'delive...",NaN,[2017-01-15],male,ODI,Pakistan,50,[Mohammad Hafeez],"[Australia, Pakistan]",bat,Australia,"[CB Gaffaney, P Wilson]",Melbourne Cricket Ground,2
2,"[{'1st innings': {'team': 'Pakistan', 'deliver...",Perth,[2017-01-19],male,ODI,Australia,50,[SPD Smith],"[Australia, Pakistan]",field,Australia,"[SD Fry, C Shamshuddin]",Western Australia Cricket Association Ground,3
3,"[{'1st innings': {'team': 'Australia', 'delive...",NaN,[2017-01-22],male,ODI,Australia,50,[DA Warner],"[Australia, Pakistan]",bat,Australia,"[CB Gaffaney, MD Martell]",Sydney Cricket Ground,4
4,"[{'1st innings': {'team': 'Australia', 'delive...",NaN,[2017-01-26],male,ODI,Australia,50,[DA Warner],"[Australia, Pakistan]",bat,Australia,"[SD Fry, C Shamshuddin]",Adelaide Oval,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2028,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Belfast,[2016-07-12],male,ODI,Afghanistan,50,NaN,"[Ireland, Afghanistan]",field,Ireland,"[AJ Neill, IN Ramage]","Civil Service Cricket Club, Stormont",2029
2029,"[{'1st innings': {'team': 'Afghanistan', 'deli...",Belfast,[2016-07-17],male,ODI,Afghanistan,50,NaN,"[Ireland, Afghanistan]",bat,Afghanistan,"[AJ Neill, C Shamshuddin]","Civil Service Cricket Club, Stormont",2030
2030,"[{'1st innings': {'team': 'Ireland', 'deliveri...",Belfast,[2016-07-19],male,ODI,Ireland,50,NaN,"[Ireland, Afghanistan]",field,Afghanistan,"[R Black, C Shamshuddin]","Civil Service Cricket Club, Stormont",2031
2031,"[{'1st innings': {'team': 'Scotland', 'deliver...",Edinburgh,[2016-08-14],male,ODI,Scotland,50,NaN,"[Scotland, United Arab Emirates]",field,United Arab Emirates,"[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",2032
2032,[{'1st innings': {'team': 'United Arab Emirate...,Edinburgh,[2016-08-16],male,ODI,Scotland,50,NaN,"[Scotland, United Arab Emirates]",bat,United Arab Emirates,"[DA Haggo, M Hawthorne]","Grange Cricket Club Ground, Raeburn Place",2033

In [4]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1799 entries, 0 to 2032
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   innings               1799 non-null   object
 1   info.city             1488 non-null   object
 2   info.dates            1799 non-null   object
 3   info.gender           1799 non-null   object
 4   info.match_type       1799 non-null   object
 5   info.outcome.winner   1708 non-null   object
 6   info.overs            1799 non-null   int64
 7   info.player_of_match  1681 non-null   object
 8   info.teams            1799 non-null   object
 9   info.toss.decision    1799 non-null   object
 10  info.toss.winner      1799 non-null   object
 11  info.umpires          1799 non-null   object
 12  info.venue            1799 non-null   object
 13  match_id              1799 non-null   int32
dtypes: int32(1), int64(1), object(12)
memory usage: 203.8+ KB

In [5]:
count = 1
delivery_df1 = pd.DataFrame()
for index, row in matches.iterrows():
    count+=1
    ball_of_match = []
    batsman = []
    bowler = []
    runs = []
    player_of_dismissed = []
    teams = []
    batting_team = []
    match_id = []
    city = []
    venue = []
    for ball in row['innings'][0]['1st innings']['deliveries']:
        for key in ball.keys():
            match_id.append(count)
            batting_team.append(row['innings'][0]['1st innings']['team'])
            teams.append(row['info.teams'])
            ball_of_match.append(key)
            batsman.append(ball[key]['batsman'])
            bowler.append(ball[key]['bowler'])
            runs.append(ball[key]['runs']['total'])
            city.append(row['info.city'])
            venue.append(row['info.venue'])
            try:
                player_of_dismissed.append(ball[key]['wicket']['player_out'])
            except:
                player_of_dismissed.append('0')
    loop_df = pd.DataFrame({
            'match_id':match_id,
            'teams':teams,
            'batting_team':batting_team,
            'ball':ball_of_match,
            'batsman':batsman,
            'bowler':bowler,
            'runs':runs,
            'player_dismissed':player_of_dismissed,
            'city':city,
            'venue':venue
        })
    delivery_df1 = pd.concat([delivery_df1, loop_df], ignore_index=True)

In [6]:
delivery_df1

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue
0,2,"[Australia, Pakistan]",Australia,0.1,DA Warner,Mohammad Amir,0,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba"
1,2,"[Australia, Pakistan]",Australia,0.2,DA Warner,Mohammad Amir,0,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba"
2,2,"[Australia, Pakistan]",Australia,0.3,DA Warner,Mohammad Amir,0,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba"
3,2,"[Australia, Pakistan]",Australia,0.4,DA Warner,Mohammad Amir,0,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba"
4,2,"[Australia, Pakistan]",Australia,0.5,DA Warner,Mohammad Amir,1,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba"
...,...,...,...,...,...,...,...,...,...,...
519641,1800,"[Scotland, United Arab Emirates]",United Arab Emirates,44.6,Ahmed Raza,CB Sole,0,0,Edinburgh,"Grange Cricket Club Ground, Raeburn Place"
519642,1800,"[Scotland, United Arab Emirates]",United Arab Emirates,45.1,Fayyaz Ahmed,AC Evans,1,0,Edinburgh,"Grange Cricket Club Ground, Raeburn Place"
519643,1800,"[Scotland, United Arab Emirates]",United Arab Emirates,45.2,Ahmed Raza,AC Evans,0,0,Edinburgh,"Grange Cricket Club Ground, Raeburn Place"
519644,1800,"[Scotland, United Arab Emirates]",United Arab Emirates,45.3,Ahmed Raza,AC Evans,0,0,Edinburgh,"Grange Cricket Club Ground, Raeburn Place"
519645,1800,"[Scotland, United Arab Emirates]",United Arab Emirates,45.4,Ahmed Raza,AC Evans,0,Ahmed Raza,Edinburgh,"Grange Cricket Club Ground, Raeburn Place"

In [7]:
def bowl(row):
    for team in row["teams"]:
        if team != row["batting_team"]:
            return team

In [8]:
delivery_df1["bowling_team"] = delivery_df1.apply(bowl , axis=1)

In [9]:
delivery_df1

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,"[Australia, Pakistan]",Australia,0.1,DA Warner,Mohammad Amir,0,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba",Pakistan
1,2,"[Australia, Pakistan]",Australia,0.2,DA Warner,Mohammad Amir,0,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba",Pakistan
2,2,"[Australia, Pakistan]",Australia,0.3,DA Warner,Mohammad Amir,0,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba",Pakistan
3,2,"[Australia, Pakistan]",Australia,0.4,DA Warner,Mohammad Amir,0,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba",Pakistan
4,2,"[Australia, Pakistan]",Australia,0.5,DA Warner,Mohammad Amir,1,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba",Pakistan
...,...,...,...,...,...,...,...,...,...,...,...
519641,1800,"[Scotland, United Arab Emirates]",United Arab Emirates,44.6,Ahmed Raza,CB Sole,0,0,Edinburgh,"Grange Cricket Club Ground, Raeburn Place",Scotland
519642,1800,"[Scotland, United Arab Emirates]",United Arab Emirates,45.1,Fayyaz Ahmed,AC Evans,1,0,Edinburgh,"Grange Cricket Club Ground, Raeburn Place",Scotland
519643,1800,"[Scotland, United Arab Emirates]",United Arab Emirates,45.2,Ahmed Raza,AC Evans,0,0,Edinburgh,"Grange Cricket Club Ground, Raeburn Place",Scotland
519644,1800,"[Scotland, United Arab Emirates]",United Arab Emirates,45.3,Ahmed Raza,AC Evans,0,0,Edinburgh,"Grange Cricket Club Ground, Raeburn Place",Scotland
519645,1800,"[Scotland, United Arab Emirates]",United Arab Emirates,45.4,Ahmed Raza,AC Evans,0,Ahmed Raza,Edinburgh,"Grange Cricket Club Ground, Raeburn Place",Scotland

In [10]:
delivery_df1.drop("teams" , axis =1 , inplace =True)

In [11]:
delivery_df1["batting_team"].unique()

array(['Australia', 'Pakistan', 'Afghanistan', 'Scotland', 'Zimbabwe',
       'New Zealand', 'Bangladesh', 'South Africa', 'India', 'England',
       'Sri Lanka', 'Hong Kong', 'Papua New Guinea', 'West Indies',
       'Ireland', 'United Arab Emirates', 'Nepal',
       'United States of America', 'Namibia', 'Oman', 'Africa XI',
       'Kenya', 'Bermuda', 'Netherlands', 'Canada', 'Asia XI'],
      dtype=object)

In [12]:
teams = ["Australia",
        "Pakistan",
        "Afghanisthan",
        "New Zealand",
        "Bangladesh",
        "South Africa",
        "India",
        "England",
        "Sri Lanka",
        "Netherlands"]

In [13]:
delivery_df1 = delivery_df1[delivery_df1["batting_team"].isin(teams)]
delivery_df1 = delivery_df1[delivery_df1["bowling_team"].isin(teams)]

In [14]:
delivery_df1

,match_id,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,Australia,0.1,DA Warner,Mohammad Amir,0,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba",Pakistan
1,2,Australia,0.2,DA Warner,Mohammad Amir,0,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba",Pakistan
2,2,Australia,0.3,DA Warner,Mohammad Amir,0,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba",Pakistan
3,2,Australia,0.4,DA Warner,Mohammad Amir,0,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba",Pakistan
4,2,Australia,0.5,DA Warner,Mohammad Amir,1,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba",Pakistan
...,...,...,...,...,...,...,...,...,...,...
518126,1795,Sri Lanka,39.5,SS Pathirana,MA Starc,0,0,NaN,Pallekele International Cricket Stadium,Australia
518127,1795,Sri Lanka,39.6,SS Pathirana,MA Starc,0,0,NaN,Pallekele International Cricket Stadium,Australia
518128,1795,Sri Lanka,39.7,SS Pathirana,MA Starc,1,0,NaN,Pallekele International Cricket Stadium,Australia
518129,1795,Sri Lanka,40.1,SS Pathirana,SM Boland,0,0,NaN,Pallekele International Cricket Stadium,Australia
518130,1795,Sri Lanka,40.2,SS Pathirana,SM Boland,0,SS Pathirana,NaN,Pallekele International Cricket Stadium,Australia

In [15]:
output = delivery_df1[["match_id" , "batting_team" , "bowling_team" , "ball" , "runs" , "player_dismissed" , "city", "venue"]]

In [16]:
output

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,2,Australia,Pakistan,0.1,0,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba"
1,2,Australia,Pakistan,0.2,0,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba"
2,2,Australia,Pakistan,0.3,0,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba"
3,2,Australia,Pakistan,0.4,0,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba"
4,2,Australia,Pakistan,0.5,1,0,Brisbane,"Brisbane Cricket Ground, Woolloongabba"
...,...,...,...,...,...,...,...,...
518126,1795,Sri Lanka,Australia,39.5,0,0,NaN,Pallekele International Cricket Stadium
518127,1795,Sri Lanka,Australia,39.6,0,0,NaN,Pallekele International Cricket Stadium
518128,1795,Sri Lanka,Australia,39.7,1,0,NaN,Pallekele International Cricket Stadium
518129,1795,Sri Lanka,Australia,40.1,0,0,NaN,Pallekele International Cricket Stadium
518130,1795,Sri Lanka,Australia,40.2,0,SS Pathirana,NaN,Pallekele International Cricket Stadium

In [17]:
pickle.dump(output , open("dataset_2.pkl" , "wb"))